# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177rhoci0_QbEkmyFn39Hp2rbYH_cIKmW
"""

import pandas as pd
baza={
    "FISH":["Majidov Sh","Tojaliyev.M","Alimqulov A","Talabov Z","Xalilov J","Mo'ysinov M","Husanov.Y","Turgunova.K","Nuriddinjonov I","Majidova Sh"],
    "Manzili":["Namangan viloyati","Fargona viloyati","Namangan viloyati","Namangan viloyati","Namangan viloyati","Namangan viloyati","Fargona viloyati","Fargona viloyati","Fargona viloyati","Namangan viloyati"],
    "Yoshi":["19","45","19","19","19","19","1","19","99","19"],
    "ish joyi":["Student","Student","Student","Student","Student","Student","Student","Student","Student","Student"],
    "Jinsi":["erkak","erkak","erkak","erkak","erkak","erkak","erkak","ayol","erkak","ayol"]
}
db=pd.DataFrame(baza)
print (db)

filtr=db[db['Jinsi']=="ayol"]
print(filtr)

filtr=db[db['Yoshi']>="20"]
print(filtr)

filtr=db[db['Manzili']=="Fargona viloyati"]
print(filtr)